backend = "glx";

vsync = true;

shadow = true;

inactive-opacity = 1;

active-opacity = 1;

blur-method = "dual_kawase";

blur-strength = 7;

corner-radius = 1;

corner-radius-rules = [
	#"20:class_g = 'Com.github.xournalpp.xournalpp'"
	"13:class_g = 'org.gnome.clocks'",
	"13:name = 'Properties'",
	"13:name = 'Properties'",
	"14:window_type = 'popup_menu'",
	"14:window_type = 'combo'"
];

opacity-rule = [
	#"100:window_type = 'dock'",
	#"85:class_g = 'kitty'",
	#"95:class_g = 'Zathura'",
	#"80:class_g = 'Org.gnome.Nautilus'",
	"90:class_g = 'Org.gnome.clocks'",
	"80:class_g = 'Gnome-pomodoro'"
]

shadow-exclude = [
	"class_g = 'Rofi'",
	"class_g = 'Dunst'",
	"class_g = 'PureRef'",
	#"window_type = 'dropdown_menu'",
	#"window_type = 'popup_menu'", 
	"window_type = 'menu'",
	#"window_type = 'dock'",
	"window_type = 'utility'",
	"window_type = 'dnd'" # drag windows
]

rounded-corners-exclude = [
	"window_type = 'dock'",
	#"window_type = 'popup_menu'",
	#"window_type = 'dropdown_menu'",
	"window_type = 'menu'",
	"window_type = 'combo'", # form
	"window_type = 'dnd'", # drag windows
	"window_type = 'utility'",
	"window_type = 'tooltip'",
	#"window_type = 'dialog'",
	"widthb>1800 && heightb>1000",
	"widthb=1344 && heightb=1048",
	"widthb=576 && heightb=1048",
	"widthb=576 && heightb=524",
	"widthb=960 && heightb=1048",
	"widthb=1152 && heightb=1048",
	"widthb=768 && heightb=1048",
	"class_g = 'vlc'",
	"class_g = 'kdenlive'",
	"class_g = 'Eog'",
	"class_g = 'Audacity'",
	"class_g = 'Onboard'",
	"class_g = 'xdg-desktop-portal-gnome'",
	"class_g = 'flipflip'",
	"class_g = 'krita'",
	"class_g = 'Gnome-pomodoro'",
	"class_g = 'Dunst'",
	"class_g = 'Zathura'"
];

blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'dropdown_menu'", 
	"window_type = 'menu'", 
	"window_type = 'popup_menu'", 
	"window_type = 'utility'",
	"window_type = 'tooltip'",
	"window_type = 'dnd'", # drag windows
	"class_g = 'Onboard'",
	#"class_g = 'Rofi'",
	"class_g = 'vlc'",
	"window_type = 'dnd'", # drag windows
	"class_g = 'Dunst'",
	"class_g = 'slop'",
	"class_g = 'zoom'"
];

#wintypes:
#{
	 #popup_menu = { shadow = true; opacity = 1; full-shadow = false; }
	 #dnd = { shadow = false; opacity = 0; full-shadow = false; }
	 #utility = { shadow = true; opacity = 1; full-shadow = true; }
	 #tooltip = { shadow = false; opacity = 1; full-shadow = false; }
#};
