backend = "glx";

use-damage = true;

vsync = true;

shadow = true;

inactive-opacity = 1;

active-opacity = 1;

blur-method = "dual_kawase";

blur-strength = 7;

corner-radius = 0;

corner-radius-rules = [
	"13:class_g = 'org.gnome.clocks'",
	"13:class_g = 'paleta'",
	"6:class_g = 'Rofi'",
	"13:name = 'Properties'",
	"13:name = 'File Conflict'",
	"14:window_type = 'combo'" #forms
];

opacity-rule = [
	"90:class_g = 'Org.gnome.clocks'",
	"80:class_g = 'Gnome-pomodoro'"
]

shadow-exclude = [
	"class_g = 'Rofi'",
	"class_g = 'Dunst'",
	"class_g = 'PureRef'",
	#"window_type = 'dropdown_menu'",
	#"window_type = 'popup_menu'", 
	"window_type = 'menu'",
	#"window_type = 'dock'",
	"window_type = 'utility'",
	"window_type = 'normal' && class_g = 'org.gnome.Nautilus'" #drag windows
]

blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'dropdown_menu'", 
	"window_type = 'menu'", 
	"window_type = 'popup_menu'", 
	"window_type = 'utility'",
	"window_type = 'tooltip'",
    "window_type = 'normal' && 
    class_g != 'Rofi'
    && class_g != 'Zathura'
    && class_g != 'Gnome-pomodoro'
    ", #drag windows
	"class_g = 'Onboard'",
	"class_g = 'vlc'",
	"window_type = 'dnd'", # drag windows
	"class_g = 'Dunst'",
	"class_g = 'slop'",
	"class_g = 'zoom'"
];
