[general]
import = [
    "~/.config/alacritty/themes/base16-tomorrow-night.toml"
]

# [window]
# opacity = 0.7

[font]
size = 9.4

[font.bold]
family = "JetBrainsMonoNL NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NFM"
# style = "Bold"
