[general]
import = [
    "~/.config/alacritty/themes/base16-tomorrow-night.toml"
]

[window]
# opacity = 0.9
padding.x = 8
padding.y = 8

[font]
size = 11
# size = 11.6

[font.normal]
# family = "JetBrainsMono NL NFM"
family = "Mx437 IBM VGA 8x16"
style = "SemiBold"

[font.bold]
# family = "JetBrainsMono NL NFM"
family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.bold_italic]
# family = "JetBrainsMono NL NFM"
family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"

[font.italic]
# family = "JetBrainsMono NL NFM"
family = "Mx437 IBM VGA 8x16"
style = "Italic"
