[general]
import = [
    "~/.config/alacritty/themes/base16-tomorrow-night.toml"
]

# [window]
# opacity = 0.7
# padding.x = 12
# padding.y = 12

[font]
# size = 9.6
size = 11.6

[font.normal]
family = "Mx437 IBM VGA 8x16"
style = "Regular"

[font.bold]
family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.bold_italic]
family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"

[font.italic]
family = "Mx437 IBM VGA 8x16"
style = "Italic"
