[general]
import = [
    "~/.config/alacritty/themes/base16-tomorrow-night.toml"
]

[window]
# opacity = 0.9
padding.x = 16
padding.y = 16

[font]
size = 11.6

[font.normal]
family = "Iosevka NFM"
# family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.bold]
family = "Iosevka NFM"
# family = "Mx437 IBM VGA 8x16"
style = "ExtraBold"

[font.bold_italic]
family = "Iosevka NFM"
# family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"

[font.italic]
family = "Iosevka NFM"
# family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"
