[general]
import = [
    "~/.config/alacritty/themes/base16-tomorrow-night.toml"
]

# [window]
# opacity = 0.7
# padding.x = 12
# padding.y = 12

[font]
size = 9.7
# size = 11.6

[font.normal]
family = "JetBrainsMono NL NFM"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono NL NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NL NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NL NFM"
style = "Italic"
